2025-04-21 09:38:27,079 INFO run_step_utils.py:318 Starting command is: /groups/pupko/yairshimony/microbializer/pipeline/steps/mmseqs_v4/mmseqs2_create_db.py /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/outputs/tmp/05_1_mmseqs_dbs/job_inputs/19.txt /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/outputs/steps_results/02_1_orfs/orfs_translated /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/outputs/steps_results/05_1_mmseqs_dbs -v False --logs_dir /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/outputs/tmp/05_1_mmseqs_dbs --error_file_path /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/M1CR0B1AL1Z3R_outputs/error.txt --job_name 19_mmseqs_dbs --use_job_manager True --cpus 1
2025-04-21 09:38:27,325 INFO mmseqs2_create_db.py:20 Calling: mmseqs createdb /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/outputs/steps_results/02_1_orfs/orfs_translated/Chlamydia_psittaci_6BC.faa /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/outputs/steps_results/05_1_mmseqs_dbs/Chlamydia_psittaci_6BC.db --dbtype 1 -v 1
2025-04-21 09:40:26,483 INFO mmseqs2_create_db.py:23 /groups/pupko/yairshimony/microbializer_runs/chlamydia_run_a/outputs/steps_results/05_1_mmseqs_dbs/Chlamydia_psittaci_6BC.db was created successfully.
   RunTime=00:02:08 TimeLimit=1-00:00:00 TimeMin=N/A
   NumNodes=1 NumCPUs=2 NumTasks=1 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
