2025-04-19 01:54:32,473 INFO run_step_utils.py:318 Starting command is: /home/ai_center/ai_users/yairshimony/microbializer/pipeline/steps/mmseqs_v4/mmseqs2_create_db.py /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/outputs/tmp/05_1_mmseqs_dbs/job_inputs/1.txt /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/outputs/steps_results/02_1_orfs/orfs_translated /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/outputs/steps_results/05_1_mmseqs_dbs -v False --logs_dir /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/outputs/tmp/05_1_mmseqs_dbs --error_file_path /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/M1CR0B1AL1Z3R_outputs/error.txt --job_name 1_mmseqs_dbs --use_job_manager True --cpus 1
2025-04-19 01:54:32,475 INFO mmseqs2_create_db.py:20 Calling: mmseqs createdb /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/outputs/steps_results/02_1_orfs/orfs_translated/Ecoli_JJ1886.faa /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/outputs/steps_results/05_1_mmseqs_dbs/Ecoli_JJ1886.db --dbtype 1 -v 1
2025-04-19 01:54:34,186 INFO mmseqs2_create_db.py:23 /home/ai_center/ai_users/yairshimony/microbializer_runs/5_genomes/outputs/steps_results/05_1_mmseqs_dbs/Ecoli_JJ1886.db was created successfully.
   RunTime=00:00:03 TimeLimit=5-00:00:00 TimeMin=N/A
   NumNodes=1 NumCPUs=1 NumTasks=1 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
